### ISSUE TITLE
write a README tutorial to start developing javascript

### ISSUE THREAD

**Issue by gabrielperales** [codingforeveryone/READMEs#11]
Through gitter @san00 asked me about how to run javascript code in a code editor.

I think we can help newbies writing a readme about how to start developing javascript with online platforms like jsbin, jsfiddle and how to install  [_brew_](https://github.com/Homebrew/homebrew), [_nvm_](https://github.com/creationix/nvm) and setup some code editors like _Atom_, _Visual Studio Code_, _Sublime Text_ and others.

**Comment by mcelearr** [comment]
@gabrielperales That sounds like a great idea!

**Comment by gabrielperales** [comment]
I have self assigned this issue to me, but if somebody wants to join... they will be welcome :)

**Comment by daymos** [comment]
I can contribute how to run nodeJS in sublime

**Comment by gabrielperales** [comment]
@daymos great, I will tell you when I start  writting my readme.

**Comment by matthewglover** [comment]
This sounds a really good idea. I was thinking of doing a readme on setting up a basic testing environment, which might complement your readme, but let me know if I can help in any way.

**Comment by san00** [comment]
Yes, this is a really good idea, I'm happy to help too, maybe I could suggest other newbie issues/topics that you could write about or I could point out and ask for further explanation to be included for some of the things you may write about in the Readme files. Please let me know.

**Comment by gabrielperales** [comment]
@san00 I'll be glad to listen yours suggestions. I'm going to start writing a long this week or this weekend, but meanwhile, you can still asking me about how to setup your environment through gitter :)
