### ISSUE TITLE
Contribution Workflow is unclear

### ISSUE THREAD

**Issue by njsfield** [codingforeveryone/READMEs#171]
Hey,

I'm a bit new, and I was following the guidelines on the Contribution Workflow instructions to use branches instead of forking the repository, but was unable to push my branch to the origin. 

Gabriel on Gitter mentioned this method doesn't work and advised I fork, as this method is more for team members with their own permissions.

Please clarify that new users should fork :)

Thanks

**Comment by ozym11** [comment]
Hi,

I didn't have any issues with the method proposed in contribution-workflow.md. Perhaps I can help you figure out what went wrong if you elaborate on your process.
