### ISSUE TITLE
Review + Feedback for Reg exp beginners guide

### ISSUE THREAD

**Issue by RichAWarren** [codingforeveryone/READMEs#22]
Looking for feedback on my [regular expression beginners guide](https://github.com/codingforeveryone/READMEs/blob/RegExp-Beginners-Guide/regular-expressions-beginners-guide.md).

Let me know if there is anything that should be amended/added - thanks!

**Comment by daymos** [comment]
It's really well written. It clarified some points to me, and  I will use it as a reference when I don't remember something. 
I think the section about parentheses does a good job to introduce the topic, but it could be expanded. Just from the explanation there I cannot understand well how the example works.
But then maybe it wont be a beginner's guide any longer..

**Comment by RichAWarren** [comment]
Thanks for your feedback! I will have a further look at the parentheses section and see if I can make it a little clearer, its not an area that I'm 100% on so could do with further research!

**Comment by RichAWarren** [comment]
I've amend the parentheses section on the master, copied below for ease:

## Using Parenthesized Substring Matches

A slightly more advanced, yet incredibly useful, technique. Including parentheses (a pair of brackets) in a regular expression pattern causes the corresponding submatch (the pattern within the brackets) to be remembered. For example, /a(b)c/ matches the characters 'abc' and remembers 'b'. The nine most recent mataches are stored under and can be recalled using the notation $n (where n is an integer from 1-9).

The following script uses the replace() method to switch the words in the string. For the replacement text, the script uses the $1 and $2 in the replacement to denote the first and second parenthesized substring matches.

```
var re = /(\w+)\s(\w+)/;
var str = "John Smith";
var newstr = str.replace(re, "$2, $1");
console.log(newstr);
```

The (\w+) matches and stores a pattern of alphanumeric characters up until a white space or the end of string. So $1 = "John" and $2 = "Smith". Therefore the newstr replaces any occurance of "John Smith" with "$2, $1" (or "Smith, John"). So console log will print "Smith, John".

Do you think this any clearer? Its a very difficult topic to explain simply!!

**Comment by daymos** [comment]
Yes, i got it now! Awesome job
