### ISSUE TITLE
Remove inactive remote branches

### ISSUE THREAD

**Issue by gabrielperales** [codingforeveryone/READMEs#25]
Hi, I have seen that there are some remote branches that has been **merged** with master branch.

Should we remove them?

![branches](https://cloud.githubusercontent.com/assets/1859128/13255205/49629f6c-da45-11e5-84d0-00a3904c00af.png)

**Comment by coudrew** [comment]
I can't think of any reason not to.

**Comment by mcelearr** [comment]
I'm not sure what the etiquette on GitHub is for. I would say remove them once they are merged. But maybe it should be up to the person who made the PR? I'm not sure tbh!

**Comment by gabrielperales** [comment]
@mcelearr Yes, that is what I think. I have removed mine, but there are more and we should keep this repo clean. I'm going to tell it to @RichAWarren

**Comment by RichAWarren** [comment]
All removed now! Cheers guys!
