### ISSUE TITLE
Add an Index to the main README?

### ISSUE THREAD

**Issue by gabrielperales** [codingforeveryone/READMEs#32]
We are starting to have a lot of READMEs. Should we add an Index with links to each README into the main [README](https://github.com/codingforeveryone/READMEs/blob/master/README.md) of this repo?

Probably we can create one by topics, or from beginners to experts.

**Comment by daymos** [comment]
Seems a good idea to me. I would vote for one by topic.

**Comment by coudrew** [comment]
I agree, it's going to start getting out of hand soon. I also vote for topic, but as time goes on, maybe have beginner/expert within the topics?

**Comment by mcelearr** [comment]
I like the idea of an index by topic too. How do people feel about the following topics:

#### Javascript
- array-map.md
- best-js-resources.md
- math-object-beginner-guide.md
- recursive-function.md
- regular-expressions-beginners-guide.md
- string-dissection-and-manipulation.md

#### Programmer skills
- command-line.md
- git-basics.md
- hoisting.md
- hosting-on-github-gh-pages.md
- markdown-cheat-sheet.md
- start-to-develop-js.md

#### Codewars
- writing-your-own-kata.md
- random-test-cases-for-complete-beginners.md

Obviously this is based on the readmes we have at the moment and should be updated as new readmes on other topics are added.

**Comment by webtechalex** [comment]
I think those topics are sensible.
I personally think we may be getting a little carried away with the readmes
and it would be helpful to limit their scope so that we can concentrate on
improving relevance and quality over quantity. I'm of course open to
objections to my view but I would suggest, once we decide on categories, we
make them final.

**Comment by coudrew** [comment]
I'm getting the feeling we're inadvertently writing an eBook called _Coding for Everyone_. Maybe we should approach it from that viewpoint to determine/maintain structure?

**Comment by sofer** [comment]
Anyone for a gitbook?

Just in case, I have created a pr: https://github.com/codingforeveryone/READMEs/pull/44 to get started

**Comment by sofer** [comment]
http://codingforeveryone.foundersandcoders.org/ waiting for content.

**Comment by coudrew** [comment]
I've merged @sofer 's gitbook summary and I'm gonna work on a rough skeleton by topic. Should I create a new issue regarding that?
