### ISSUE TITLE
readme working with multiple desktop

### ISSUE THREAD

**Issue by daymos** [codingforeveryone/READMEs#39]
I will write how to use mission control ( mac). If someone uses multiple desktops on windows, like virtuaWin, or equivalent features on linux and feel like contributing let me know.

**Comment by iteles** [comment]
@daymos Is this also a good place to add using something like [Spectacle](https://www.spectacleapp.com/) to organise your windows within one desktop as well?

**Comment by daymos** [comment]
Yes absolutely.  Maybe I will rename it to productivity utilities? Or if you have a better name to propose please tell me

**Comment by daymos** [comment]
@iteles I have worked a bit on this, but it seems I don't have enough material to write a reasonable readme. If you don't have objection I think I will close this issue and think about a new topic
