### ISSUE TITLE
Write a README with a small tutorial about git

### ISSUE THREAD

**Issue by gabrielperales** [codingforeveryone/READMEs#4]
Resources:
- [Git Pro](https://git-scm.com/book/en/v2) Ebook
- [Try Git](https://www.codeschool.com/courses/try-git) Free interactive online course
- [Learn Git Branching](http://pcottle.github.io/learnGitBranching/) Free interactive online course
- [Git Cheat Sheet](https://www.git-tower.com/blog/git-cheat-sheet/) Cheat Sheet PDF

Current WIP document [here](https://github.com/gabrielperales/READMEs/blob/git_basics/git-basics.md)

**Comment by sofer** [comment]
@gabrielperales here's some more:
- Natalia's [Introduction to Git and Version Control](https://github.com/NataliaLKB/learn-git-basics)
- [Resolving a merge conflict from the command line](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)

**Comment by gabrielperales** [comment]
@sofer oh!, Natalia's is good enough to use it as a README in this repo...

**Comment by sofer** [comment]
@gabrielperales Natalia's README is just great, but a really simple intro to git would not hurt.

Something like this perhaps: https://github.com/selforganising/foundersandcoders/blob/gh-pages/_posts/2014-04-08-git.md
