### ISSUE TITLE
readme on linked list

### ISSUE THREAD

**Issue by daymos** [codingforeveryone/READMEs#49]

**Comment by RichAWarren** [comment]
Created pull request to your master, changed if functions syntax & typos

**Comment by daymos** [comment]
so should I approve the pull request now?

**Comment by RichAWarren** [comment]
If you're happy with my changes yeah!

**Comment by daymos** [comment]
I cannot see your commit. The last one I see is 7837876 which is mine

**Comment by daymos** [comment]
Ok got it. Merged into my fork. I can approve the merge on remote master not. 
You think not using brakets is a bad practice in for loops?
