### ISSUE TITLE
Writing your own kata markdown formatting

### ISSUE THREAD

**Issue by mcelearr** [codingforeveryone/READMEs#5]
It would be good to improve some of the markdown formatting in the 'writing your own kata' guide. https://github.com/codingforeveryone/READMEs/blob/master/writing-your-own-kata.md
- Centre-align the larger images
- Allow text to wrap around the two smaller images (one - just above golden rule 2 and two - just below step)
- Make the hyperlinks work - at the moment, they don't seem to be coming out right.

**Comment by daymos** [comment]
ok, tomorrow I'll work on it

**Comment by daymos** [comment]
I have researched the topic  of wrapping text around images and found out that that you can embed html tag in the markdown with in line css. I I managed to do it, and it works locally on my machine. However when I upload it on github, it's not working. I inspected the code and the style tag is not there. I found a question on stackoverflow, and it seems that github strips intentionally the style tags, for consistency/safety reasons. 
So, the other option is to use some markdown commands to do it, but they are not supported by the markdown engine used in github.  I am not confident it is possible...

**Comment by mcelearr** [comment]
Okay thanks for looking into that - valuable to know. How about adding that learning to the markdown cheatsheet? I will close this issue.

**Comment by mcelearr** [comment]
Just something small at the bottom like:
"HTML style tags can be applied locally to have a wider range of effects but be aware that github will strip these for consistency/safety reasons. See [this](link) stackoverflow question for more detail."

**Comment by daymos** [comment]
The markdown cheatsheet is an ongoing project for me. I will add this and more stuff as time goes on.

**Comment by daymos** [comment]
But feel free to add things yourself if you come across valuable info

**Comment by mcelearr** [comment]
:+1:
