### ISSUE TITLE
Coding for Everyone gitbook maintenance

### ISSUE THREAD

**Issue by coudrew** [codingforeveryone/READMEs#53]
So the READMEs have been organized into a [gitbook](http://codingforeveryone.foundersandcoders.org/index.html). Revisions to the READMEs within won't require any alterations to the gitbook, but adding new files means SUMMARY.md will need to be updated. Thoughts on how to manage that?

**Comment by daymos** [comment]
I think the person that accept the pull request could do it

**Comment by RichAWarren** [comment]
@daymos agreed! I've the summary for pull requests i've accepted.

Gitbook looks great btw!

**Comment by coudrew** [comment]
sounds good, and thanks!
