### ISSUE TITLE
Using sensible names for READMEs

### ISSUE THREAD

**Issue by sofer** [codingforeveryone/READMEs#7]
@JakubSvihla you might want to rename https://github.com/codingforeveryone/READMEs/blob/master/Random%20Test%20Cases%20for%20Complete%20Beginners%20-%20Short%20Introduction.

_"Sensible names are all lower-case, do not have spaces or non-ASCII characters and end with the .md file extension"_ (from https://github.com/codingforeveryone/READMEs/blob/master/README.md)

**Comment by gabrielperales** [comment]
@sofer So... [MarkdownCheatSheet.md ](https://github.com/codingforeveryone/READMEs/blob/master/MarkdownCheatSheet.md) must be renamed to _lower-case_ too, musn't it?

**Comment by sofer** [comment]
@gabrielperales that would be my suggestion, although it is also a matter of taste.

**Comment by mcelearr** [comment]
I think if we get into good habits early on it will be clear to people contributing what the convention is. Created a PR to fix the two file names
