### ISSUE TITLE
tutorial on hosting static pages on github

### ISSUE THREAD

**Issue by daymos** [codingforeveryone/READMEs#8]

**Comment by sofer** [comment]
@daymos :+1: This is a great topic. A pointer to https://pages.github.com/ would be a good start.

**Comment by daymos** [comment]
@sofer ok, thanks for the links.

**Comment by daymos** [comment]
@sofer just created the pull request. I have covered the use of gh-pages with html, and just scratched the surface of Jekyll. Do you think a tutorial on Jekyll could be useful as a follow up to this?
