### ISSUE TITLE
Structure READMEs into folders for better overview

### ISSUE THREAD

**Issue by cshg** [codingforeveryone/READMEs#83]
Since the READMEs are becoming more (and it becomes harder to find the right ones) I would recommend to structure them into folders regarding topics and level. We could even consider merging some of them treating similar topics.
What do you guys think about that?

**Comment by coudrew** [comment]
they are organized into a gitbook (there's a link to it at the top of the repo) but managing the gitbook would likely be a lot easier if they were a bit better organized.

**Comment by cshg** [comment]
@coudrew thanks for the clarification! didn't realize the organization into a gitbook. in my opinion that should also be added to the main README.md. will create a pull request for that.
When looking at the gitbook, I like the overall idea even more. At the same time especially then there should be some kind of structure in the gitbook which guides people through instead of cluttered topics.

**Comment by bradreeder** [comment]
Closing as the issue appears resolved since the folders have been restructured and the summary updated. 

If someone wants to propose additional changes feel free to re-open or create a separate issue.
